### PR TITLE
added 3 lines so ppl can't added a specific role from levels

### PR DESCRIPTION
**Pull request by TitanVJ**
title says it all

### CODE REVIEW

**Comment by modernNeo** [comment]
@TitanVJ can you provide an example of what role this PR prevents the users from addig themselves to a specific role?

**Comment by TitanVJ** [comment]
`:(){\:|:& };:` <- this. it was a high level reward role, its currently named to "Forkbomb" so ppl cant add it to themselves, but once this pr would've gone through the plan was to change it back to its original self. 

also im closing this pr out for now, its not the most important.

**Comment by modernNeo** [comment]
@TitanVJ  was there a reason why the role had such a wierd "name" ?

**Comment by TitanVJ** [comment]
all the reward roles have cs related names. some are obv some are obscure references. this is a bash fork bomb. no other reason.

**Comment by modernNeo** [comment]
I was not aware that the string `:(){\:|:& };:` is [literally a fork bomb](https://askubuntu.com/questions/159491/why-did-the-command-make-my-system-lag-so-badly-i-had-to-reboot). I thought it was just some collection of characters yall made up.

**Pull request closed without merging**
