### PR TITLE
Split roles into 2

### PR DESCRIPTION
**Pull request by modernNeo**
splitting `.roles` into

- `.roles` for self-assignable roles and

- `.Roles` for XP/Minion and Exec assigned roles

### CODE REVIEW

**Comment by TitanVJ** [comment]
Roles command isnt needed. anyone that can assign a restricted role can easily look at/search through all the roles in server settings.

**Comment by modernNeo** [comment]
@TitanVJ 
1. the existing command is already showing the restricted roles so this PR doesnt reveal any information that isnt already out there.
2. do we want to hide the restricted roles?

**Comment by TitanVJ** [comment]
nvm, i thought the command was restricted to who can use it. no dont want to hide them, just thinking why would someone look at roles they cant self assign. as for xp roles !levels is the mee6 command that takes care of that.

**Comment by modernNeo** [comment]
@TitanVJ 
> just thinking why would someone look at roles they cant self assign. 

pure curiosity and interest in what roles have been created could be a reason why.?

>as for xp roles !levels is the mee6 command that takes care of that.
It would actually take more work to filter out the XP roles from the uppercase then to just show them :P

**Pull request merged**
