### PR TITLE
Server leaderboard web app

### PR DESCRIPTION
**Pull request by wnfldchen**
## Description
The popularly requested server leaderboard web app is now ready to go live. A testing link will be posted under this PR as a comment once this PR is opened and the corresponding deployment pipeline has finished.

The application is a R Shiny dashboard and a Python discord.py script both in a separate docker container from the actual Wall-E discord bot. The R Shiny dashboard depends on the user points data from the database container and a user name cache populated by the Python discord.py script, which when run connects to the discord guild to retrieve the guild members as part of discord.py's default client initialization process if the cache is older than one hour. The R Shiny dashboard is a reactive application, which only updates the leaderboard when a visitor clicks the refresh link. A refresh always retrieves the latest user points data from the database container, but only updates the user name cache if it has expired. The cache expiry time of one hour was chosen to limit discord token authentications to at most 24 in one day, well under applicable limits.

Therefore, after the refresh link is clicked, it is possible for a user to be present in the user points data, but not the user name cache if the click happens less than one hour after the previous click. Such users as well as users who are no longer guild members are displayed with their discord `user id` instead of `username#discriminant nickname`.

The docker container exposes the R Shiny dashboard on the default port 3838. The master production version will be assigned a static internal ip of 192.168.168.169 using the deployment pipeline. The host nginx reverse proxy will pass the leaderboard web directory location to the container and port. The docker containers corresponding to test versions will not be publicly accessible due to the only feasible approach being to expose them on ephemeral host ports directly to the public internet, which could be very many open ports and running processes if many branches are open.

No changes have been made to the actual Wall-E discord bot - the only changes in this PR are to the deployment pipeline and to the new web application container. Future additions to the web interface of Wall-E also using R Shiny dashboards such as more server statistics tracking and analytics should be made inside this web application container.

## PR Checklist

These are the things you need to ensure are covered in your PR, otherwise the CODEOWNERS will not approve your PR, not matter how much you ping them to do so on the Discord  
  
 1. The description in the PR is a fair representation of what the PR is about.
 1. The PR is fixing one thing and one thing only.
 1. Logging. if you have N variables initialzed/used in your function, you should print all of them out to the log using logging module at least once or have a good reason why you arent.
 1. If your PR is doing something like adding a new line or removing a new line, CODEOWNERS reserve the right to ask that you undo that change unless it was for a specific reason.
 1. If you are adding a new command....document. Document the following things on help.json and the README.md
    1. The purpose of the command
    1. If the argument is called with any arguments.
       1. If it is called with any arguments, please either provide a good enough explanation of the arg that a user can tell what it will do before using the command. adding an example of how to call it with the args is not necessary but good practice.
 1. If you are making a new Class of commands, add the class to bot.json following the convention already there.
 1. Evidence of Testing. This one needs to be completed after the PR is opened. At that point, you will go on the channel on the CSSS Wall-E Test Server that was automatically created when the PR was opened and then test the [following functionality](https://github.com/CSSS/wall_e/blob/master/documentation/Working_on_Bot/Test_Cases.md). Once you had done so, you can leave a comment on the PR stating that you had done the necessary testing.
 1. Please provide ways to test whatever you just modified on the bot in the [Test Cases section](https://github.com/CSSS/wall_e/blob/master/documentation/Working_on_Bot/Test_Cases.md) so that future PRs can be tested to ensure they dont break your code when merging to master

### CODE REVIEW

**Comment by modernNeo** [comment]
@wnfldchen can you change it so the leaderboards at `https://jenkins.sfucsss.org/PR-<pr_number>/leaderboard/` ?

**Comment by wnfldchen** [comment]
No, I can't make that automatically happen for each PR, it is not feasible to do that. The only container which will be publicly accessible will be the master version. For this time only I manually made this PR's version publicly accessible in the same way the master version will be for testing purposes- it wasnt the PR pipeline that made that link, but the master pipeline will.

**Comment by modernNeo** [comment]
> it is not feasible to do that.

In what sense?

**Comment by wnfldchen** [comment]
Jenkins would have to modify the nginx reverse proxy configuration each PR and reload nginx, which is risky because Jenkins is itself behind the same reverse proxy. Basically, we would have to wait for the container to come up, grab the container's IP, dynamically generate an nginx configuration file from a template with the right ip and web directory substituted in, save it, and then reload nginx. When the container is replaced, the IP might change, so the configuration has to change as well. When the PR is closed, change as well. So I wouldnt say infeasible, but it greatly increases the risk that something goes wrong. It could be done though. Do you actually want this? This isnt even talking about the end result yet: when the tester goes to the link, they'll just see a blank leaderboard, because additional work will be needed by the pipeline to inject some user points data into the test db- which is something that you had mentioned you were working on, so I guess you have some stuff for that.

**Comment by modernNeo** [comment]
@wnfldchen 

> Jenkins would have to modify the nginx reverse proxy configuration each PR and reload nginx, which is risky because Jenkins is itself behind the same reverse proxy.

Why would you consider that being risky? its not like Jenkins uses the nginx servce for any of the calls it makes. csss-site is doing the same thing here 🙃 [I grant you its a hack-solution but not bad imo given our limited resouces]

https://github.com/CSSS/csss-site/blob/3d4bee4bb239c035eac3e0c31a38e8968e4aad06/CI/validate_and_deploy/2_deploy/2_deploy_staging_changes.sh#L144-L170

> Basically, we would have to wait for the container to come up, grab the container's IP, dynamically generate an nginx configuration file from a template with the right ip and web directory substituted in, save it, and then reload nginx. When the container is replaced, the IP might change, so the configuration has to change as well.

The nginx config does not need the IP of the container. we can do this too
```
upstream wall_e_pr_<number> {
    server <container_number>:<port to talk to wall_e on> fail_timeout=0;
}
```

> Do you actually want this? 

It's doable, and would make testing it easier.

> This isnt even talking about the end result yet: when the tester goes to the link, they'll just see a blank leaderboard, because additional work will be needed by the pipeline to inject some user points data into the test db- which is something that you had mentioned you were working on, so I guess you have some stuff for that.

Exactly, I do plan to have the staging guild load the points from master 😄

**Comment by modernNeo** [comment]
```
REPOSITORY                 TAG       IMAGE ID       CREATED             SIZE
test_web_wall_e_web        latest    eec53ae5cd96   47 hours ago        1.69GB
```
good Lord that's a big one...

**Comment by modernNeo** [comment]
@wnfldchen is this waiting on me or you?

**Comment by modernNeo** [comment]
@wnfldchen rebase off of master to get access to the PROD data

**Comment by modernNeo** [comment]
@wnfldchen 
> Testing link (and future permanent link): https://jenkins.sfucsss.org/leaderboard/

this isn't working?

**Comment by modernNeo** [comment]
@wnfldchen status check?

**Comment by wnfldchen** [comment]
@modernNeo thanks for the reminder i will get back to this

**Comment by modernNeo** [comment]
closing as won't do per Winfield's comments on discord

**Pull request closed without merging**
