### PR TITLE
Vj SFU Cog

### PR DESCRIPTION
**Pull request by TitanVJ**
# SFU commands are here
Praise

## Added sfu command
* It returns calendar description from the current semester of the arg
* Usage: `.sfu <arg>`
    * Ex: `.sfu cmpt300`

## Added outline command
* It returns outline detail of the arg, optionally you can specify term and/or section
* Usage: `.outline <arg0> [<arg1> <arg2>]`
    * Ex: `.outline cmpt300 spring d200`

## All the thing have been updated to go along with these commands.
* Entries in : 
    * help.json
    * cogs.json
    * README.md
    * My soul

### CODE REVIEW

**Comment by TitanVJ** [comment]
@modernNeo fixed

**Comment by modernNeo** [comment]
@TitanVJ this broke it `.outline phi 100w`

**Comment by TitanVJ** [comment]
@modernNeo fixed. so now u can do `.outline cmpt 300 spring d200` and it wont break

**Comment by modernNeo** [comment]
this breaks it too `.outline dumb`

**Comment by TitanVJ** [comment]
@modernNeo should be all fixed

**Comment by brenfan** [comment]
For determining the year and term, you can just pass in `current` or `registration` as the year and term and the outlines API will do the hard work for you.

http://www.sfu.ca/outlines/help/api.html

**Comment by TitanVJ** [comment]
@brenfan ty for info. 
gonna close this pr while i do some edge case work and other things on this one.

**Pull request closed without merging**
