### PR TITLE
broken PR being left open for investigation of what went wrong

### PR DESCRIPTION
**Pull request by modernNeo**

### CODE REVIEW

**Comment by modernNeo** [comment]
@wnfldchen what broke here?

**Comment by wnfldchen** [comment]
It's so weird how it'll break for like one PR very super rarely but not the rest

**Comment by wnfldchen** [comment]
I noticed and looking at it

**Comment by modernNeo** [comment]
@wnfldchen but what did I do that caused it?

**Comment by modernNeo** [comment]
@wnfldchen I am leaving this open for you to investigate what went wrong if you want to. apart from that.

**Comment by wnfldchen** [comment]
It somehow fixed itself after my commit! It may have been the merge conflict breaking it. Because, Jenkins will try to do the merge and then send the merged version to the test server but if there's a merge conflict it might not report back the pass/fail (infinite wait). So I might add a build timeout to Jenkins, we'll see.

**Comment by wnfldchen** [comment]
Where after the timeout it autofails, maybe

**Pull request closed without merging**
